export const DEFAULT_APP_NAME = "demo";
export const DEFAULT_APP_ID = "6421563c21169e32c89017a0";

export const SUPPORTED_TYPES = [
  "top",
  "bottom",
  "footwear",
  "outfit",
  "hair",
  "eye",
  "eyeshape",
  "eyebrows",
  "faceshape",
  "noseshape",
  "lipshape",
  "glasses",
  "headwear",
  "beard",
  "facewear",
  "facemask",
];

export const SUPPORTED_GENDERS = ["male", "female"];

export const PRESET_SPECS = {
  male: [
    { id: "preset-1", label: "01", imageHint: "white-male-1.png" },
    { id: "preset-2", label: "02", imageHint: "black-male-1.png" },
    { id: "preset-3", label: "03", imageHint: "asian-male-1.png" },
    { id: "preset-4", label: "04", imageHint: "indian-male-1.png" },
    { id: "preset-5", label: "05", imageHint: "white-male-2.png" },
    { id: "preset-6", label: "06", imageHint: "black-male-2.png" },
    { id: "preset-7", label: "07", imageHint: "asian-male-2.png" },
    { id: "preset-8", label: "08", imageHint: "indian-male-2.png" },
    { id: "preset-9", label: "09", imageHint: "white-male-3.png" },
    { id: "preset-10", label: "10", imageHint: "black-male-3.png" },
    { id: "preset-11", label: "11", imageHint: "asian-male-3.png" },
    { id: "preset-12", label: "12", imageHint: "indian-male-3.png" },
    { id: "preset-13", label: "13", imageHint: "onboarding-asian-male-1.png" },
    { id: "preset-14", label: "14", imageHint: "onboarding-black-male-1.png" },
    { id: "preset-15", label: "15", imageHint: "onboarding-asian-male-2.png" },
    { id: "preset-16", label: "16", imageHint: "onboarding-black-male-2.png" },
    { id: "preset-17", label: "17", imageHint: "onboarding-white-male-1.png" },
    { id: "preset-18", label: "18", imageHint: "onboarding-indian-male-1.png" },
    { id: "preset-19", label: "19", imageHint: "onboarding-other-male-1.png" },
    { id: "preset-20", label: "20", imageHint: "onboarding-white-male-2.png" },
  ],
  female: [
    { id: "preset-1", label: "01", imageHint: "white-female-1.png" },
    { id: "preset-2", label: "02", imageHint: "black-female-1.png" },
    { id: "preset-3", label: "03", imageHint: "asian-female-1.png" },
    { id: "preset-4", label: "04", imageHint: "indian-female-1.png" },
    { id: "preset-5", label: "05", imageHint: "white-female-2.png" },
    { id: "preset-6", label: "06", imageHint: "black-female-2.png" },
    { id: "preset-7", label: "07", imageHint: "asian-female-2.png" },
    { id: "preset-8", label: "08", imageHint: "indian-female-2.png" },
    { id: "preset-9", label: "09", imageHint: "white-female-3.png" },
    { id: "preset-10", label: "10", imageHint: "black-female-3.png" },
    { id: "preset-11", label: "11", imageHint: "asian-female-3.png" },
    { id: "preset-12", label: "12", imageHint: "indian-female-3.png" },
    { id: "preset-13", label: "13", imageHint: "onboarding-indian-female-1.png" },
    { id: "preset-14", label: "14", imageHint: "onboarding-indian-female-2.png" },
    { id: "preset-15", label: "15", imageHint: "onboarding-asian-female-1.png" },
    { id: "preset-16", label: "16", imageHint: "onboarding-white-female-1.png" },
    { id: "preset-17", label: "17", imageHint: "onboarding-asian-female-2.png" },
    { id: "preset-18", label: "18", imageHint: "onboarding-asian-female-3.png" },
    { id: "preset-19", label: "19", imageHint: "onboarding-indian-female-3.png" },
    { id: "preset-20", label: "20", imageHint: "onboarding-asian-female-4.png" },
  ],
};
